/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author Alumno
 */
public class Menu extends javax.swing.JDialog {

    /**
     * Creates new form Menu
     */
    public Menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAgregarPersona = new javax.swing.JMenuItem();
        itemVerPrestamosPersona = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAgregarLibro = new javax.swing.JMenuItem();
        itemAgregarEjemplar = new javax.swing.JMenuItem();
        itemAgregarTipo = new javax.swing.JMenuItem();
        itemEjemplaresDisponibles = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemRegistroPrestamo = new javax.swing.JMenuItem();
        itemRegistroDevolucion = new javax.swing.JMenuItem();
        itemConsultarPrestamosPersona = new javax.swing.JMenuItem();
        itemListarPrestamos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("jMenu3");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Biblioteca 111mil");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Biblioteca");

        jMenu1.setText("Persona");

        itemAgregarPersona.setText("Agregar");
        itemAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarPersonaActionPerformed(evt);
            }
        });
        jMenu1.add(itemAgregarPersona);

        itemVerPrestamosPersona.setText("Ver prestamos");
        itemVerPrestamosPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerPrestamosPersonaActionPerformed(evt);
            }
        });
        jMenu1.add(itemVerPrestamosPersona);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Libro");

        itemAgregarLibro.setText("Agregar libro");
        itemAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarLibroActionPerformed(evt);
            }
        });
        jMenu2.add(itemAgregarLibro);

        itemAgregarEjemplar.setText("Agregar ejemplar");
        itemAgregarEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarEjemplarActionPerformed(evt);
            }
        });
        jMenu2.add(itemAgregarEjemplar);

        itemAgregarTipo.setText("Agregar tipo de libro");
        itemAgregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarTipoActionPerformed(evt);
            }
        });
        jMenu2.add(itemAgregarTipo);

        itemEjemplaresDisponibles.setText("Consultar ejemplares disponibles");
        itemEjemplaresDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEjemplaresDisponiblesActionPerformed(evt);
            }
        });
        jMenu2.add(itemEjemplaresDisponibles);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Prestamo");

        itemRegistroPrestamo.setText("Registro");
        itemRegistroPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroPrestamoActionPerformed(evt);
            }
        });
        jMenu4.add(itemRegistroPrestamo);

        itemRegistroDevolucion.setText("Devolución");
        itemRegistroDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroDevolucionActionPerformed(evt);
            }
        });
        jMenu4.add(itemRegistroDevolucion);

        itemConsultarPrestamosPersona.setText("Consultar prestamos por persona");
        itemConsultarPrestamosPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarPrestamosPersonaActionPerformed(evt);
            }
        });
        jMenu4.add(itemConsultarPrestamosPersona);

        itemListarPrestamos.setText("Listar prestamos");
        itemListarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarPrestamosActionPerformed(evt);
            }
        });
        jMenu4.add(itemListarPrestamos);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarLibroActionPerformed
        //registrarNuevoLibro();
        RegistrarLibro registerBook = new RegistrarLibro(null, true);
        registerBook.setVisible(true);
    }//GEN-LAST:event_itemAgregarLibroActionPerformed

    private void itemAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarPersonaActionPerformed
        // TODO add your handling code here:
        // registrarPersona();
        AltaPersona ap = new AltaPersona(null, true);
        ap.setVisible(true);
    }//GEN-LAST:event_itemAgregarPersonaActionPerformed

    private void itemVerPrestamosPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerPrestamosPersonaActionPerformed
        ConsultaEjemplaresPrestados Ce = new ConsultaEjemplaresPrestados(null, true);
        Ce.setVisible(true);
    }//GEN-LAST:event_itemVerPrestamosPersonaActionPerformed

    private void itemRegistroDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroDevolucionActionPerformed
        // TODO add your handling code here:
        DevolucionEjemplar de = new DevolucionEjemplar(null, true);
        de.setVisible(true);
    }//GEN-LAST:event_itemRegistroDevolucionActionPerformed

    private void itemAgregarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarEjemplarActionPerformed
        //registrarEjemplar();
        InterfazdeEjemplares E = new InterfazdeEjemplares(null, true);
        E.setVisible(true);
    }//GEN-LAST:event_itemAgregarEjemplarActionPerformed

    private void itemRegistroPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroPrestamoActionPerformed
        GuiPrestamo p = new GuiPrestamo(null, true);
        p.setVisible(true);
    }//GEN-LAST:event_itemRegistroPrestamoActionPerformed

    private void itemConsultarPrestamosPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarPrestamosPersonaActionPerformed
        ConsultaEjemplaresPrestados Ce = new ConsultaEjemplaresPrestados(null, true);
        Ce.setVisible(true);
    }//GEN-LAST:event_itemConsultarPrestamosPersonaActionPerformed

    private void itemEjemplaresDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEjemplaresDisponiblesActionPerformed
        GuiListarEjemplares le = new GuiListarEjemplares(null, true);
        le.setVisible(true);
    }//GEN-LAST:event_itemEjemplaresDisponiblesActionPerformed

    private void itemListarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarPrestamosActionPerformed
        ListadoPrestamos list = new ListadoPrestamos(null, true);
        list.setVisible(true);
    }//GEN-LAST:event_itemListarPrestamosActionPerformed

    private void itemAgregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarTipoActionPerformed
        GUITipoLibro tp = new GUITipoLibro(null, true);
        tp.setVisible(true);
    }//GEN-LAST:event_itemAgregarTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu dialog = new Menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAgregarEjemplar;
    private javax.swing.JMenuItem itemAgregarLibro;
    private javax.swing.JMenuItem itemAgregarPersona;
    private javax.swing.JMenuItem itemAgregarTipo;
    private javax.swing.JMenuItem itemConsultarPrestamosPersona;
    private javax.swing.JMenuItem itemEjemplaresDisponibles;
    private javax.swing.JMenuItem itemListarPrestamos;
    private javax.swing.JMenuItem itemRegistroDevolucion;
    private javax.swing.JMenuItem itemRegistroPrestamo;
    private javax.swing.JMenuItem itemVerPrestamosPersona;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
